define({
    root: ({
        baseMapLabels: ({
            imagery: "Imagery",
            imagery_with_labels: "Imagery with Labels",
            streets: "Streets",
            topographic: "Topographic",
            dark_gray_canvas: "Dark Gray Canvas",
            light_gray_canvas: "Light Gray Canvas",
            //national_geographic: "National Geographic",
            oceans: "Oceans",
            terrain_with_labels: "Terrain with Labels",
            openstreetmap: "Open Street Map",
        })
    }),
    "ar": 0,
    "cs": 0,
    "da": 0,
    "de": 0,
    "el": 0,
    "es": 0,
    "et": 0,
    "fi": 0,
    "fr": 1,
    "he": 0,
    "it": 0,
    "ja": 0,
    "ko": 0,
    "lt": 0,
    "lv": 0,
    "nl": 0,
    "nb": 0,
    "pl": 0,
    "pt-br": 0,
    "pt-pt": 0,
    "ro": 0,
    "ru": 0,
    "sv": 0,
    "tr": 0,
    "th": 0,
    "vi": 0,
    "zh-cn": 0
});
